### ISSUE TITLE
Installing plugin fails with: fork/exec ./nozzle-plugin-linux: permission denied

### ISSUE THREAD

**Issue by jyidiego** [cloudfoundry/firehose-plugin#16]
When i try to install this plugin on Ubuntu 14.04 - 4.2.0-35 kernel version. I get the following errors:

cf --version
cf version 6.16.1+924508c-2016-02-26

cf install-plugin nozzle-plugin-linux -f

Installing plugin ./nozzle-plugin-linux
FAILED
fork/exec ./nozzle-plugin-linux: permission denied

**Comment by jtuchscherer** [comment]
@jyidiego Sorry for the late response. I just came across this issue. Apparently, we don't have the Pivotal Tracker integration set up for this repo.

If you download the plugin from the github release page, you will have to make it executable first, e.g. `chmod +x ./nozzle-plugin-linux`.

Otherwise, you could just follow the instruction in the README and download the plugin from the community repo.

Let me know if that fixes your problem, so that we can close this issue.

**Comment by wfernandes** [comment]
@jyidiego Let us know if you still are unable to install the plugin.
